site_name: Bitzquad Academy Documentation
site_url: https://docs.learn.bitzquad.com
nav:
  - Home: index.md
  - About: about.md
theme:
  name: material
  highlightjs: true
  font:
    text: Inter
  logo: img/logo-white.png
  favicon: img/favicon.png
  features:
    - navigation.tracking
    - navigation.top
    - toc.follow
    - toc.integrate
